### ISSUE TITLE
ReduceLROnPlateau

### ISSUE THREAD

**Issue by eshankn** [MaximIntegratedAI/ai8x-training#333]
Hello, I would like to use the ReduceLROnPlateau learning rate scheduler for my training. I have also created the relevant scheduler YAML file. However, while performing the step() update, there is an error on [line](https://github.com/analogdevicesinc/distiller/blob/0477a66ef0ace09f5572f27c0178ea422ed9bf4e/distiller/policy.py#L311).

I receive a `KeyError: 'metrics'`. Is there some additional parameter missing when using the ReduceLROnPlateau scheduler? There is not much documentation regarding this nor the other example scripts use this scheduler.

The scheduler YAML file looks like this.
```
---
lr_schedulers:
  training_lr:
    class: ReduceLROnPlateau
    mode: min
    factor: 0.1
    patience: 5

policies:
  - lr_scheduler:
      instance_name: training_lr
    starting_epoch: 0
    ending_epoch: 200
    frequency: 1
```
